# Dependencies
gems:                [jekyll-paginate]
markdown:            kramdown
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               EAGERFloodlight
tagline:             'Messing with your routing tables since September 2016.'
url:                 https://github.com/cbarrin/EAGERFloodlight
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Geddings Barrineau
  url:               https://github.com/cbarrin
  email:             cbarrin@g.clemson.edu

# Custom vars
version:             1.0.0

github:
  repo:              https://github.com/cbarrin/EAGERFloodlight

exclude:             ["src"]